typography_spectrum: 0.7181053943932056
color:
  brandStrength: 0.45467778970487416
  lightness: 0.8280322144273669
  saturation: 0.29302230454050004
  rhythmicContrast: 0.2797161836642772
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
layout_spectrum: 0.8075384916737676
name: Adopt a Diet
title: It's a simple idea...
description: Adopt a simple diet and donate the money you save.
